import { Lightbulb, Monitor, TouchpadOff, LayoutGrid, UtensilsCrossed, Sun } from 'lucide-react'

export const types = [
    {
        id: 1,
        icon: Lightbulb,
        badge: 'High Brightness',
        badgeColor: '#fbbf24',
        badgeBg: 'rgba(251,191,36,0.12)',
        badgeBorder: 'rgba(251,191,36,0.3)',
        title: 'LED Displays',
        label: 'Vibrant · Energy Efficient',
        description:'LED displays deliver exceptional brightness, vivid colour accuracy, and long operational lifespans — making them ideal for high-traffic environments where impact matters. Ultra-thin bezels and modular panel designs allow for seamless large-format installations.',
        highlights: ['Up to 100,000hr lifespan', 'Ultra-high brightness', 'Modular panel design'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(251,191,36,0.25), rgba(45,74,107,0.9))',
    },
    {
        id: 2,
        icon: Monitor,
        badge: 'Versatile',
        badgeColor: '#93c5fd',
        badgeBg: 'rgba(147,197,253,0.12)',
        badgeBorder: 'rgba(147,197,253,0.3)',
        title: 'LCD Screens',
        label: 'Sharp · Cost-Effective',
        description:
        'LCD screens are the most widely deployed digital signage format — offering sharp resolution, wide viewing angles, and competitive pricing. Available in portrait or landscape orientations, they suit retail, corporate lobbies, and waiting areas.',
        highlights: ['4K resolution options', 'Wide viewing angles', 'Portrait & landscape'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(147,197,253,0.2), rgba(45,74,107,0.9))',
    },
    {
        id: 3,
        icon: TouchpadOff,
        badge: 'Interactive',
        badgeColor: '#5eead4',
        badgeBg: 'rgba(94,234,212,0.12)',
        badgeBorder: 'rgba(94,234,212,0.3)',
        title: 'Interactive Kiosks',
        label: 'Self-Service · Engaging',
        description: 'Interactive kiosks turn passive viewers into active users. With multi-touch screens, wayfinding maps, self-checkout, and product discovery tools — kiosks reduce staff workload while improving the customer experience.',
        highlights: ['Multi-touch display', 'Wayfinding & self-checkout', 'ADA compliant options'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(94,234,212,0.2), rgba(45,74,107,0.9))',  
    },
    {
        id: 4,
        icon: LayoutGrid,
        badge: 'Large Format',
        badgeColor: '#a78bfa',
        badgeBg: 'rgba(167,139,250,0.12)',
        badgeBorder: 'rgba(167,139,250,0.3)',
        title: 'Video Walls',
        label: 'Immersive · Impactful',
        description:'Video walls combine multiple displays into a single seamless canvas — creating immersive brand experiences at scale. Used in control rooms, broadcast studios, retail flagships, and event spaces. Bezel-free and ultra-thin configurations available.',
        highlights: ['Seamless bezel-free joins', 'Any size configuration', 'Control room ready'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(167,139,250,0.25), rgba(45,74,107,0.9))',
    },
    {
        id: 5,
        icon: UtensilsCrossed,
        badge: 'Food & Retail',
        badgeColor: '#4ade80',
        badgeBg: 'rgba(74,222,128,0.12)',
        badgeBorder: 'rgba(74,222,128,0.3)',
        title: 'Menu Boards',
        label: 'Dynamic · Appetising',
        description:'Digital menu boards let hospitality and retail businesses update pricing, promotions, and availability instantly — no printing, no delay. Daypart scheduling automatically switches content for breakfast, lunch, and dinner without manual input.',
        highlights: ['Instant price updates', 'Daypart scheduling', 'POS integration ready'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(74,222,128,0.2), rgba(45,74,107,0.9))',    
    },
    {
        id: 6,
        icon: Sun,
        badge: 'Weatherproof',
        badgeColor: '#f87171',
        badgeBg: 'rgba(248,113,113,0.12)',
        badgeBorder: 'rgba(248,113,113,0.3)',
        title: 'Outdoor Digital Displays',
        label: 'Rugged · All-Weather',
        description:'Outdoor displays are engineered to perform in rain, dust, direct sunlight, and extreme temperatures. High-brightness panels (up to 5,000 nits) ensure visibility in full daylight, while IP65-rated enclosures protect hardware year-round.',
        highlights: ['Up to 5,000 nit brightness', 'IP65 weatherproof rated', 'Anti-glare coating'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(248,113,113,0.2), rgba(45,74,107,0.9))',
    },
];