import { MonitorPlay, Zap, Film, Clock, LayoutGrid, BarChart2,
  Lightbulb, Monitor, TouchpadOff, UtensilsCrossed, Sun,
  Cloud, ShoppingCart, Code2, Radio, ArrowRight
} from 'lucide-react'

export const features = [
    {
    id: 'cms',
    span: 2,
    strong: true,
    icon: MonitorPlay,
    color: '#93c5fd',
    pill: 'Core module',
    eyebrow: 'Content Management',
    headline: 'One CMS. Every screen.',
    body: 'Upload, organise, and push content to any screen from a single cloud CMS — no on-site visits, no local servers, no complexity.',
    bullets: [
      'Drag & drop editor with live preview',
      'Role-based access for teams and clients',
      'Version history with one-click rollback',
      'Bulk publish to any screen or group',
    ],
    stats: [['Cloud', 'Native'], ['Role-Based', 'Access'], ['Version', 'History']],
  },
  {
    id: 'realtime',
    span: 1,
    strong: false,
    icon: Zap,
    color: '#4ade80',
    pill: 'Instant delivery',
    eyebrow: 'Live Updates',
    headline: 'Any change. Live in seconds.',
    body: 'Push content updates, emergency alerts, or price changes to any screen in under 5 seconds — no caching delays, no manual refresh.',
    bullets: [
      'Sub-5s delivery to all connected screens',
      'Emergency override — interrupts any playlist',
      'Targeted push by screen, group, or location',
    ],
    stats: [['< 5s', 'Delivery'], ['Zero', 'Downtime'], ['Instant', 'Override']],
  },
  {
    id: 'media',
    span: 1,
    strong: false,
    icon: Film,
    color: '#a78bfa',
    pill: 'All formats',
    eyebrow: 'Media Support',
    headline: 'Every format, natively.',
    body: 'Video, images, animations, HTML5 widgets, and live RTSP streams — all supported out of the box without third-party plugins.',
    bullets: [
      'MP4, WebM, GIF & APNG video formats',
      'PNG, JPG & SVG static assets',
      'HTML5 widgets & CSS animations',
      'Live RTSP & HLS stream input',
    ],
    stats: [['6+', 'Formats'], ['HTML5', 'Widgets'], ['Live', 'RTSP']],
  },
  {
    id: 'schedule',
    span: 2,
    strong: true,
    icon: Clock,
    color: '#fbbf24',
    pill: 'Set & forget',
    eyebrow: 'Playback Scheduling',
    headline: 'Right content. Right moment.',
    body: "Define exactly when each piece of content plays — by time, day, date range, or recurring rule. The platform handles the rest.",
    bullets: [
      'Time-of-day and day-of-week triggers',
      'Date-range campaigns with auto-expiry',
      'Priority override for urgent content',
      'Conflict detection & schedule validation',
    ],
    stats: [['Recurring', 'Rules'], ['Auto', 'Expiry'], ['Priority', 'Override']],
  },
  {
    id: 'multiscreen',
    span: 2,
    strong: true,
    icon: LayoutGrid,
    color: '#5eead4',
    pill: 'At scale',
    eyebrow: 'Screen Management',
    headline: 'Unlimited screens. One dashboard.',
    body: 'Manage every screen across every location from a single view — group them by zone, sync them, or override individually.',
    bullets: [
      'Unlimited screens across unlimited locations',
      'Group sync — push to a zone in one click',
      'Per-screen content & schedule override',
      'Online / idle / offline health monitoring',
    ],
    stats: [['Unlimited', 'Screens'], ['Group', 'Sync'], ['Health', 'Monitoring']],
  },
  {
    id: 'analytics',
    span: 1,
    strong: true,
    icon: BarChart2,
    color: '#93c5fd',
    pill: 'Data driven',
    eyebrow: 'Engagement Insights',
    headline: 'See what resonates.',
    body: 'Screen-level view counts, dwell time, interaction rates, and campaign performance — everything you need to optimise content.',
    bullets: [
      'Per-screen views & average dwell time',
      'Campaign performance over custom ranges',
      'Interaction & touch-event tracking',
      'CSV export for offline reporting',
    ],
    stats: [['Real-Time', 'Data'], ['Campaign', 'Reports'], ['CSV', 'Export']],
  },
]

export const types = [
  {
    id: 'led',
    icon: Lightbulb,
    color: '#00e5a0',
    label: 'High-Brightness Display',
    badge: 'Most Popular',
    title: 'LED Displays',
    description: 'Vibrant, energy-efficient LED panels built for high-impact visuals — indoors or out. Ideal for retail frontages, lobbies, and large-format advertising.',
    highlights: ['Ultra-bright up to 10,000 nits', 'Seamless modular build', 'Low power consumption', '24/7 operation ready'],
    specs: [['10,000', 'nits'], ['P1.2', 'Pixel pitch'], ['24/7', 'Operation']],
    cols: 2,
  },
  {
    id: 'lcd',
    icon: Monitor,
    color: '#7ab8ff',
    label: 'Commercial Grade',
    badge: 'Versatile',
    title: 'LCD / Commercial Screens',
    description: 'Professional-grade LCD screens for indoor environments — sharp, reliable, and built for continuous use in retail, offices, and hospitality.',
    highlights: ['400–700 nit brightness', 'Portrait & landscape', 'Anti-glare coating'],
    specs: [['700', 'nits'], ['60Hz', 'Refresh']],
    cols: 1,
  },
  {
    id: 'kiosk',
    icon: TouchpadOff,
    color: '#f0a33c',
    label: 'Interactive',
    badge: 'Self-Service',
    title: 'Interactive Kiosks',
    description: 'Touchscreen kiosks that let customers browse, order, check in, or get information — reducing queue times and staff workload.',
    highlights: ['10-point multitouch', 'ADA compliant options', 'Integrated payments'],
    specs: [['10pt', 'Touch'], ['IP54', 'Rating']],
    cols: 1,
  },
  {
    id: 'videowall',
    icon: LayoutGrid,
    color: '#c09aff',
    label: 'Large Format',
    badge: 'Premium',
    title: 'Video Walls',
    description: 'Multi-panel video walls that create immersive, large-scale visual experiences — perfect for control rooms, showrooms, and flagship retail.',
    highlights: ['Near-zero bezel joins', 'Scalable from 2×2 up', 'Single or multi-source input', 'Content synchronisation'],
    specs: [['0.9mm', 'Bezel gap'], ['2×2+', 'Scalable'], ['4K', 'Per panel']],
    cols: 2,
  },
  {
    id: 'menuboard',
    icon: UtensilsCrossed,
    color: '#ff8775',
    label: 'Food & Beverage',
    badge: 'QSR Ready',
    title: 'Digital Menu Boards',
    description: 'Dynamic menu boards that update in seconds — switch pricing, promote specials, and schedule daypart menus without printing a thing.',
    highlights: ['Instant remote updates', 'Daypart scheduling', 'POS integration ready', 'Portrait or landscape'],
    specs: [['<5s', 'Update time'], ['∞', 'Playlists'], ['500', 'nits']],
    cols: 2,
  },
  {
    id: 'outdoor',
    icon: Sun,
    color: '#60c8f0',
    label: 'Weatherproof',
    badge: 'IP65 Rated',
    title: 'Outdoor Displays',
    description: 'IP65-rated screens built for rain, dust, and direct sunlight — delivering crisp visuals in car parks, forecourts, and building exteriors.',
    highlights: ['2,500–5,000 nit brightness', 'IP65 weatherproof', 'Operating temp -30°C to 60°C'],
    specs: [['5,000', 'nits'], ['IP65', 'Rated']],
    cols: 1,
  },
]

// Tech Integration stuff

export const platforms = [
  { name: 'Screenly',   color: '#4ade80', status: 'Connected' },
  { name: 'NoviSign',   color: '#60a5fa', status: 'Connected' },
  { name: 'Rise Vision', color: '#f472b6', status: 'Available' },
  { name: 'Yodeck',     color: '#fb923c', status: 'Available' },
]

export const endpoints = [
  { method: 'GET',    path: '/api/screens',         color: '#4ade80' },
  { method: 'POST',   path: '/api/content/push',    color: '#60a5fa' },
  { method: 'PATCH',  path: '/api/schedule/:id',    color: '#fbbf24' },
  { method: 'DELETE', path: '/api/playlist/:id',    color: '#f87171' },
]

export const posItems = [
  { name: 'Americano', price: '£3.20', cycle: 0 },
  { name: 'Latte',     price: '£3.80', cycle: 1 },
  { name: 'Croissant', price: '£2.50', cycle: 2 },
]


export const cards = [
  {
    id: 'cms',
    icon: Cloud,
    color: '#00e5a0',
    eyebrow: 'Content Management',
    headline: 'Cloud CMS Integration',
    pill: '2 Active',
    body: 'Connect your preferred digital signage CMS and push content to any screen — remotely, in real time, from one dashboard.',
    highlights: ['Screenly, NoviSign, Yodeck & more', 'Remote playlist management', 'Role-based publishing access'],
    mockup: 'cms',
    cols: 2,
  },
  {
    id: 'pos',
    icon: ShoppingCart,
    color: '#f0a33c',
    eyebrow: 'Point of Sale',
    headline: 'POS Sync',
    pill: 'Live',
    body: 'Prices and menu items update on-screen the moment they change in your POS — no manual edits, no mismatches.',
    highlights: ['Real-time price sync', 'Automatic menu updates', 'Supports Square, Lightspeed & more'],
    mockup: 'pos',
    cols: 1,
  },
  {
    id: 'api',
    icon: Code2,
    color: '#c09aff',
    eyebrow: 'Developer',
    headline: 'REST API Access',
    pill: 'Open',
    body: 'Full REST API so your dev team can push content, trigger playlists, and control screens from any internal system.',
    highlights: ['Authenticated endpoints', 'Webhook support', 'Swagger docs included'],
    mockup: 'api',
    cols: 1,
  },
  {
    id: 'datafeed',
    icon: Radio,
    color: '#60c8f0',
    eyebrow: 'Live Data',
    headline: 'Data Feed Display',
    pill: 'Real-time',
    body: 'Pull in live data — weather, exchange rates, footfall counters, sports scores — and display it dynamically on any screen.',
    highlights: ['JSON / XML feed support', 'Auto-refresh intervals', 'Custom widget templates'],
    mockup: 'datafeed',
    cols: 2,
  },
]

