import { Lightbulb, 
        Monitor, 
        TouchpadOff,
        LayoutGrid, 
        UtensilsCrossed, 
        Sun, 
        MessageSquare, 
        MonitorCheck,
        Wrench, 
        LayoutTemplate, 
        HeadphonesIcon,
        Cloud, 
        ShoppingCart, 
        Plug, 
        Radio, 
        Sliders, 
        Shield, 
        MousePointerClick, 
    } from 'lucide-react'

import {CloudCmsMockup, PosMockup, ApiMockup, DataFeedMockup} from './IntegrationComponents'

export const types = [
    {
        id: 1,
        icon: Lightbulb,
        badge: 'High Brightness',
        badgeColor: '#fbbf24',
        badgeBg: 'rgba(251,191,36,0.12)',
        badgeBorder: 'rgba(251,191,36,0.3)',
        title: 'LED Displays',
        label: 'Vibrant · Energy Efficient',
        description:'LED displays deliver exceptional brightness, vivid colour accuracy, and long operational lifespans — making them ideal for high-traffic environments where impact matters. Ultra-thin bezels and modular panel designs allow for seamless large-format installations.',
        highlights: ['Up to 100,000hr lifespan', 'Ultra-high brightness', 'Modular panel design'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(251,191,36,0.25), rgba(45,74,107,0.9))',
    },
    {
        id: 2,
        icon: Monitor,
        badge: 'Versatile',
        badgeColor: '#93c5fd',
        badgeBg: 'rgba(147,197,253,0.12)',
        badgeBorder: 'rgba(147,197,253,0.3)',
        title: 'LCD Screens',
        label: 'Sharp · Cost-Effective',
        description:
        'LCD screens are the most widely deployed digital signage format — offering sharp resolution, wide viewing angles, and competitive pricing. Available in portrait or landscape orientations, they suit retail, corporate lobbies, and waiting areas.',
        highlights: ['4K resolution options', 'Wide viewing angles', 'Portrait & landscape'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(147,197,253,0.2), rgba(45,74,107,0.9))',
    },
    {
        id: 3,
        icon: TouchpadOff,
        badge: 'Interactive',
        badgeColor: '#5eead4',
        badgeBg: 'rgba(94,234,212,0.12)',
        badgeBorder: 'rgba(94,234,212,0.3)',
        title: 'Interactive Kiosks',
        label: 'Self-Service · Engaging',
        description: 'Interactive kiosks turn passive viewers into active users. With multi-touch screens, wayfinding maps, self-checkout, and product discovery tools — kiosks reduce staff workload while improving the customer experience.',
        highlights: ['Multi-touch display', 'Wayfinding & self-checkout', 'ADA compliant options'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(94,234,212,0.2), rgba(45,74,107,0.9))',  
    },
    {
        id: 4,
        icon: LayoutGrid,
        badge: 'Large Format',
        badgeColor: '#a78bfa',
        badgeBg: 'rgba(167,139,250,0.12)',
        badgeBorder: 'rgba(167,139,250,0.3)',
        title: 'Video Walls',
        label: 'Immersive · Impactful',
        description:'Video walls combine multiple displays into a single seamless canvas — creating immersive brand experiences at scale. Used in control rooms, broadcast studios, retail flagships, and event spaces. Bezel-free and ultra-thin configurations available.',
        highlights: ['Seamless bezel-free joins', 'Any size configuration', 'Control room ready'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(167,139,250,0.25), rgba(45,74,107,0.9))',
    },
    {
        id: 5,
        icon: UtensilsCrossed,
        badge: 'Food & Retail',
        badgeColor: '#4ade80',
        badgeBg: 'rgba(74,222,128,0.12)',
        badgeBorder: 'rgba(74,222,128,0.3)',
        title: 'Menu Boards',
        label: 'Dynamic · Appetising',
        description:'Digital menu boards let hospitality and retail businesses update pricing, promotions, and availability instantly — no printing, no delay. Daypart scheduling automatically switches content for breakfast, lunch, and dinner without manual input.',
        highlights: ['Instant price updates', 'Daypart scheduling', 'POS integration ready'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(74,222,128,0.2), rgba(45,74,107,0.9))',    
    },
    {
        id: 6,
        icon: Sun,
        badge: 'Weatherproof',
        badgeColor: '#f87171',
        badgeBg: 'rgba(248,113,113,0.12)',
        badgeBorder: 'rgba(248,113,113,0.3)',
        title: 'Outdoor Digital Displays',
        label: 'Rugged · All-Weather',
        description:'Outdoor displays are engineered to perform in rain, dust, direct sunlight, and extreme temperatures. High-brightness panels (up to 5,000 nits) ensure visibility in full daylight, while IP65-rated enclosures protect hardware year-round.',
        highlights: ['Up to 5,000 nit brightness', 'IP65 weatherproof rated', 'Anti-glare coating'],
        image: '/images/max.jpg',
        imageFallbackBg: 'linear-gradient(135deg, rgba(248,113,113,0.2), rgba(45,74,107,0.9))',
    },
];

export const steps = [
    {
        number: '01',
        icon: MessageSquare,
        title: 'Consultation',
        label: 'Understanding Your Needs',
        description: 'We begin with a thorough discovery session to understand your goals, audience, locations, and budget. Our consultants map out the right signage strategy before a single screen is specified.',
        highlights: ['Site walkthrough', 'Goals & budget review', 'Audience analysis'],
        accent: '#93c5fd',
        accentBg: 'rgba(147,197,253,0.1)',
        accentBorder: 'rgba(147,197,253,0.25)',   
    },
    {
        number: '02',
        icon: MonitorCheck,
        title: 'Display Selection',
        label: 'Right Screen for the Job',
        description: 'Based on your consultation, we recommend the best hardware — LED, LCD, outdoor, interactive, or video wall — matched precisely to your environment, footfall, and content requirements.',
        highlights: ['Hardware specification', 'Environment matching', 'Future-proof selection'],
        accent: '#a78bfa',
        accentBg: 'rgba(167,139,250,0.1)',
        accentBorder: 'rgba(167,139,250,0.25)',
    },
    {
        number: '03',
        icon: Wrench,
        title: 'Installation',
        label: 'Clean & Professional',
        description: 'Our certified engineers handle full installation — mounting, cabling, media players, and network setup — with minimal disruption to your operation. Every install is tested on-site before sign-off.',
        highlights: ['Full hardware install', 'Network & media setup', 'On-site testing'],
        accent: '#4ade80',
        accentBg: 'rgba(74,222,128,0.1)',
        accentBorder: 'rgba(74,222,128,0.25)',
    },
    {
        number: '04',
        icon: LayoutTemplate,
        title: 'Content Setup',
        label: 'Ready to Broadcast',
        description: 'We configure your CMS, load your brand assets, set up playlists, schedules, and templates — so your screens are live and looking great from day one. Training included.',
        highlights: ['CMS configuration', 'Schedule & playlist setup', 'Team training included'],
        accent: '#fbbf24',
        accentBg: 'rgba(251,191,36,0.1)',
        accentBorder: 'rgba(251,191,36,0.25)',
    },
    {
        number: '05',
        icon: HeadphonesIcon,
        title: 'Ongoing Management',
        label: 'We Stay With You',
        description: 'Post-launch, we provide remote monitoring, content updates, firmware management, and a dedicated support line — keeping your network performing at its best 24/7.',
        highlights: ['Remote monitoring', 'Content & firmware updates', '24/7 support line'],
        accent: '#5eead4',
        accentBg: 'rgba(94,234,212,0.1)',
        accentBorder: 'rgba(94,234,212,0.25)',
    },
];

export const platforms = [
    {name: "Screenly", color: "#93c5fd", status:'Connected'},
    {name: "Yodeck", color: "#4ade80", status:'Connected'},
    {name: "NoviSign", color: "#a78bfa", status:'Available'},
    {name: "ScreenCloud", color: "#fbbf24", status:'Available'},
];

export const endpoints = [
    { method: 'POST', path: '/screens/push',    color: '#4ade80' },
    { method: 'GET',  path: '/screens/status',  color: '#93c5fd' },
    { method: 'PUT',  path: '/schedule/update', color: '#fbbf24' },
    { method: 'DEL',  path: '/content/:id',     color: '#f87171' }, 
]

export const cards = [
    {
      id: 'cms',
      icon: Cloud,
      accent: '#93c5fd',
      accentBg: 'rgba(147,197,253,0.12)',
      accentBorder: 'rgba(147,197,253,0.28)',
      label: 'Cloud Infrastructure',
      title: 'Cloud CMS Platforms',
      description: 'Deploy and manage content across all your screens through industry-leading cloud CMS platforms. We integrate with Screenly, Yodeck, NoviSign, ScreenCloud and more — or connect your existing platform of choice.',
      highlights: ['Multi-platform support', 'Browser-based management', 'Auto software updates'],
      mockup: CloudCmsMockup,
      wide: true,
    },
    {
      id: 'pos',
      icon: ShoppingCart,
      accent: '#4ade80',
      accentBg: 'rgba(74,222,128,0.12)',
      accentBorder: 'rgba(74,222,128,0.28)',
      label: 'Point of Sale',
      title: 'POS System Integration',
      description: 'Sync your digital signage directly with your point-of-sale system. Menu prices, stock levels, and promotions update on screen the moment they change in your POS — no manual editing required.',
      highlights: ['Auto price sync', 'Stock-aware content', 'Works with Square, Lightspeed & more'],
      mockup: PosMockup,
      wide: false,
    },
    {
      id: 'api',
      icon: Plug,
      accent: '#a78bfa',
      accentBg: 'rgba(167,139,250,0.12)',
      accentBorder: 'rgba(167,139,250,0.28)',
      label: 'Developer-Friendly',
      title: 'API Integrations',
      description: 'Our open REST API lets developers connect any external system to your signage network. Trigger content changes, pull screen status, update schedules, and automate workflows from your own applications.',
      highlights: ['Full REST API', 'Webhook support', 'OAuth 2.0 authentication'],
      mockup: ApiMockup,
      wide: false,
    },
    {
      id: 'feeds',
      icon: Radio,
      accent: '#fbbf24',
      accentBg: 'rgba(251,191,36,0.12)',
      accentBorder: 'rgba(251,191,36,0.28)',
      label: 'Live Data',
      title: 'Real-Time Data Feeds',
      description:'Pull live data directly onto your screens — weather, currency rates, sports scores, social feeds, visitor counters, and custom business metrics. Content stays fresh and relevant without manual updates.',
      highlights: ['Weather & news feeds', 'Custom data sources', 'Auto-refresh intervals'],
      mockup: DataFeedMockup,
      wide: true,
    },
]

export const trustPoints = [
  {
    id: 1,
    icon: Sliders,
    accent: '#93c5fd',
    eyebrow: 'Tailored for You',
    title: 'Custom Display Solutions',
    description: 'No two businesses are alike. We design and configure every display system around your space, brand, and goals — from screen size and placement to content layout and scheduling.',
    stats: [
      { value: '100%', label: 'Bespoke builds' },
      { value: '50+', label: 'Install types' },
    ],
    highlights: ['Site survey & consultation', 'Brand-matched content templates', 'Scalable from 1 to 100+ screens'],
  },
  {
    id: 2,
    icon: Shield,
    accent: '#4ade80',
    eyebrow: 'Built to Last',
    title: 'Reliable Hardware',
    description: 'We source commercial-grade displays rated for 16/7 and 24/7 operation. Every unit is tested before installation, backed by manufacturer warranties and our own service guarantee.',
    stats: [
      { value: '24/7', label: 'Rated operation' },
      { value: '3yr', label: 'Avg. warranty' },
    ],
    highlights: ['Commercial-grade panels only', 'Pre-install burn-in testing', 'Redundant power options'],
  },
  {
    id: 3,
    icon: MousePointerClick,
    accent: '#a78bfa',
    eyebrow: 'No Learning Curve',
    title: 'Easy-to-Use Systems',
    description: 'Our CMS platforms are designed for everyday users — not IT departments. Update content, schedule campaigns, and manage screens from any device in minutes.',
    stats: [
      { value: '<5min', label: 'To update content' },
      { value: 'Any', label: 'Device, anywhere' },
    ],
    highlights: ['Drag-and-drop content editor', 'Remote screen management', 'Role-based access controls'],
  },
  {
    id: 4,
    icon: HeadphonesIcon,
    accent: '#fbbf24',
    eyebrow: 'Always Here',
    title: 'Full Support',
    description: 'From installation day onward, our team is on call. We offer remote monitoring, on-site servicing, staff training, and proactive maintenance — so your screens never go dark.',
    stats: [
      { value: '< 4hr', label: 'Response time' },
      { value: 'Free', label: 'Staff training' },
    ],
    highlights: ['Remote diagnostics & monitoring', 'On-site repair service', 'Dedicated account manager'],
  },
]