export {default as Features} from "./features";
export {default as Systems} from "./Systems";
export {default as TrustUs} from "./TrustUs";

export * from "./CCTVStyles";

import { Wifi, DollarSign, Radio, Shield, Target, Move, Users, Settings, Headphones, BadgeDollarSign } from 'lucide-react'

export const systems = [
    {
        id: 1,
        icon: Wifi,
        label: "Modern Internet-Based",
        title: "IP Cameras",
        description: "IP cameras transmit video data over the internet, allowing for remote access and monitoring from anywhere with an internet connection.",
        highlights: ["Up to 4K resolution", "Remote access anywhere", "AI-ready & cloud-integrated"],
        image: "/images/max.jpg",
        imageFallbackBg: "linear-gradient(135deg, rgba(77,122,163,0.5), rgba(45,74,107,0.8))",
        badge: "Most Popular",
        badgeColor: "rgba(74,222,128,0.15)",
        badgeBorder: "rgba(74,222,128,0.35)",
        badgeText: "#4ade80",
    },
    {
        id: 2,
        icon: DollarSign,
        label: "Cost-Effective - Reliable",
        title: "Analog Cameras",
        description: "Analog cameras transmit video data through coaxial cables to a digital video recorder (DVR) for storage and monitoring, offering a more affordable option for basic surveillance needs.",
        highlights: ["Reuse existing cabling", "Low upfront cost", "1080p–4MP HD quality"],
        image: "/images/max.jpg",
        imageFallbackBg: "linear-gradient(135deg, rgba(61,98,135,0.5), rgba(45,74,107,0.8))",
        badge: "Budget-Friendly",
        badgeColor: "rgba(251,191,36,0.12)",
        badgeBorder: "rgba(251,191,36,0.35)",
        badgeText: "#fbbf24",
    },
    {
        id: 3,
        icon: Radio,
        label: "Cable-Free Convenience",
        title: "Wireless CCTV Systekms",
        description: "Wireless CCTV systems use Wi-Fi or other wireless technologies to transmit video data, providing flexible installation options without the need for extensive cabling.",
        highlights: ["No data cabling required", "Battery & solar options", "4G / 5G compatible"],
        image: "/images/max.jpg",
        imageFallbackBg: "linear-gradient(135deg, rgba(77,122,163,0.5), rgba(61,98,135,0.8))",
        badge: "Easy Install",
        badgeColor: "rgba(147,197,253,0.12)",
        badgeBorder: "rgba(147,197,253,0.35)",
        badgeText: "#93c5fd",
    },  
    {
        id: 4,
        icon: Shield,
        label: "Indoor · Discreet",
        title: "Dome Cameras",
        description:
          "Dome cameras sit flush against ceilings and are designed to blend into interior environments without drawing attention. The tinted dome housing makes it difficult to tell which direction the lens is pointing — a powerful deterrent in itself. Vandal-resistant models are ideal for retail, hospitality, schools, and office spaces.",
        highlights: ["Vandal-resistant housing", "Direction-ambiguous lens", "Wide-angle coverage"],
        image: "/images/max.jpg",
        imageFallbackBg: "linear-gradient(135deg, rgba(45,74,107,0.6), rgba(29,53,87,0.9))",
        badge: "Indoor",
        badgeColor: "rgba(167,139,250,0.12)",
        badgeBorder: "rgba(167,139,250,0.35)",
        badgeText: "#a78bfa",
      },
      {
        id: 5,
        icon: Target,
        label: "Outdoor · Long-Range",
        title: "Bullet Cameras",
        description:
          "Bullet cameras are purpose-built for outdoor perimeter surveillance. Their elongated housing supports larger lenses for long-range zoom — up to 100m IR night vision — and their visible, directional design acts as a strong visual deterrent. Weather-rated to IP66/IP67, they handle rain, dust, and extreme temperatures.",
        highlights: ["100m IR night vision", "IP66/IP67 weather rated", "Strong visual deterrent"],
        image: "/images/max.jpg",
        imageFallbackBg: "linear-gradient(135deg, rgba(61,98,135,0.5), rgba(29,53,87,0.9))",
        badge: "Outdoor",
        badgeColor: "rgba(74,222,128,0.12)",
        badgeBorder: "rgba(74,222,128,0.3)",
        badgeText: "#4ade80",
      },
      {
        id: 6,
        icon: Move,
        label: "Movable · Full Coverage",
        title: "PTZ Cameras",
        description:
          "PTZ (Pan-Tilt-Zoom) cameras offer dynamic, operator-controlled or automated tracking across wide areas. A single PTZ can cover ground that would require four fixed cameras. Preset patrol routes, auto-tracking of moving subjects, and powerful optical zoom (up to 30x) make them essential for large open spaces, car parks, and live monitoring scenarios.",
        highlights: ["Up to 30x optical zoom", "Auto-tracking subjects", "Replaces multiple fixed cameras"],
        image: "/images/max.jpg",
        imageFallbackBg: "linear-gradient(135deg, rgba(77,122,163,0.6), rgba(45,74,107,0.9))",
        badge: "Full Coverage",
        badgeColor: "rgba(251,191,36,0.12)",
        badgeBorder: "rgba(251,191,36,0.3)",
        badgeText: "#fbbf24",
      },
];

export const trustPoints = [
    {
        icon: Users,
        title: "Experienced Technicians",
        description: "Our team of certified technicians has years of experience in CCTV installation and maintenance, ensuring your system is set up for optimal performance and reliability.",
        highlights: ["Fully certified & vetted", "Years of field experience", "Clean, professional installs"],
        stat: "10+",
        statLabel: "Years of Experience",
        accent: "#93c5fd",
        accentBg: "rgba(147,197,253,0.1)",
        accentBorder: "rgba(147,197,253,0.25)",
    },
    {
        icon: Shield,
        title: "High-Quality Equipemnt",
        description: "We use only top-tier CCTV equipment from trusted brands, ensuring crystal-clear footage, robust durability, and advanced features to meet your specific security needs.",
        highlights: ["Top-tier brands", "Crystal-clear footage", "Robust durability"],
        stat: "4K",
        statLabel: "Max Resolution",
        accent: "#4ade80",
        accentBg: "rgba(74,222,128,0.1)",
        accentBorder: "rgba(74,222,128,0.25)",
    },
    {
        icon: Settings,
        title: "Customised Solutions",
        description:"No two sites are the same. We design every system around your specific premises, risk profile, and budget — not a one-size-fits-all package pulled off a shelf.",
        highlights: ["Site-specific design", "Scalable architecture", "Tailored to your budget"],
        stat: "100%",
        statLabel: "Bespoke designs",
        accent: "#a78bfa",
        accentBg: "rgba(167,139,250,0.1)",
        accentBorder: "rgba(167,139,250,0.25)",
    },
    {
        icon: Headphones,
        title: "Reliable Support",
        description: "Our dedicated support team is available 24/7 to assist with any questions, troubleshooting, or maintenance needs, ensuring your CCTV system remains effective and reliable at all times.",
        highlights: ["24/7 monitoring available", "Remote diagnostics", "Fast on-site response"],
        stat: "24/7",
        statLabel: "Support Availability",
        accent: "#5eead4",
        accentBg: "rgba(94,234,212,0.1)",
        accentBorder: "rgba(94,234,212,0.25)",
    },
    {
        icon: BadgeDollarSign,
        title: "Competitive Pricing",
        description: "We offer competitive pricing on all our CCTV solutions, providing excellent value for high-quality equipment and professional installation services tailored to your budget.",
        highlights: ["Transparent quotes", "No hidden fees", "Flexible payment options"],
        stat: "Free",
        statLabel: "Quotes & Consultations",
        accent: "#fbbf24",
        accentBg: "rgba(251,191,36,0.1)",
        accentBorder: "rgba(251,191,36,0.25)",
    },
];