import {
  ScanSearch,
  LockKeyhole,
  ShieldCheck,
  Plug,
  Users,
  Activity,
  ClipboardList,
} from 'lucide-react'

export const features = [
  {
    id: 1,
    icon: ScanSearch,
    accent: '#f87171',
    eyebrow: 'Proactive Defence',
    title: 'Vulnerability Scanning',
    description:'Automated scans continuously probe your network and display infrastructure for weaknesses — flagging misconfigurations, outdated firmware, and exposure points before they can be exploited.',
    highlights: ['Scheduled & on-demand scans', 'Firmware version checks', 'Exposure risk reports'],
    stat: { value: '24/7', label: 'Continuous scanning' },
    wide: true,
  },
  {
    id: 2,
    icon: LockKeyhole,
    accent: '#93c5fd',
    eyebrow: 'Data at Rest & in Transit',
    title: 'Data Encryption',
    description:'All content, credentials, and communications are encrypted end-to-end using AES-256 and TLS 1.3 — ensuring data is unreadable even if intercepted.',
    highlights: ['AES-256 at rest', 'TLS 1.3 in transit', 'Encrypted backups'],
    stat: { value: 'AES-256', label: 'Encryption standard' },
    wide: false,
  },
  {
    id: 3,
    icon: ShieldCheck,
    accent: '#4ade80',
    eyebrow: 'Identity Verification',
    title: 'Multi-Factor Authentication',
    description:'MFA is enforced across all CMS logins and admin panels — adding a second layer of verification that blocks unauthorised access even when credentials are compromised.',
    highlights: ['TOTP & SMS support', 'Enforced for all admins', 'SSO-compatible'],
    stat: { value: 'MFA', label: 'Enforced on all logins' },
    wide: false,
  },
  {
    id: 4,
    icon: Plug,
    accent: '#a78bfa',
    eyebrow: 'Integration Security',
    title: 'Secure APIs',
    description:'Every integration point uses authenticated, rate-limited APIs with token-based access — preventing abuse, injection attacks, and unauthorised data exchange between connected systems.',
    highlights: ['OAuth 2.0 & API tokens', 'Rate limiting enforced', 'Input sanitisation'],
    stat: { value: 'OAuth 2.0', label: 'Auth standard' },
    wide: false,
  },
  {
    id: 5,
    icon: Users,
    accent: '#5eead4',
    eyebrow: 'Least Privilege Access',
    title: 'Role-Based Access Control',
    description:'Define exactly who can view, edit, publish, or manage screens. RBAC ensures staff only access what they need — reducing insider risk and accidental content changes.',
    highlights: ['Custom role definitions', 'Per-screen permissions', 'Audit trail per user'],
    stat: { value: 'RBAC', label: 'Granular permissions' },
    wide: false,
  },
  {
    id: 6,
    icon: Activity,
    accent: '#fbbf24',
    eyebrow: 'Always Watching',
    title: 'Real-Time Threat Monitoring',
    description:'Live dashboards and automated alerts surface anomalies the moment they occur — unusual login attempts, unexpected content changes, or device disconnections trigger instant notifications.',
    highlights: ['Live event dashboard', 'Instant alert notifications', 'Anomaly detection'],
    stat: { value: '<1s', label: 'Alert response time' },
    wide: true,
  },
  {
    id: 7,
    icon: ClipboardList,
    accent: '#fb923c',
    eyebrow: 'Compliance & Assurance',
    title: 'Security Audits',
    description:'Regular third-party and internal audits verify that your signage infrastructure meets industry compliance standards — with full documentation provided for regulatory reporting.',
    highlights: ['Annual third-party audits', 'Compliance documentation', 'Remediation support'],
    stat: { value: 'Annual', label: 'Full audit cycle' },
    wide: true,
  },
];