import { ShieldAlert, Lock, KeyRound, Plug, Users, Activity, ClipboardList,
    AppWindow, Cloud, Plug2, UserCheck, DatabaseZap,
    ShieldCheck, Bug, Rocket,  
 } from 'lucide-react'

export const features = [
  {
    id: 'vulnerability',
    icon: ShieldAlert,
    color: '#00e5a0',
    eyebrow: 'Threat Detection',
    title: 'Vulnerability Scanning',
    body: 'Automated scans run continuously across your signage network — flagging misconfigurations, outdated firmware, and known CVEs before they become incidents.',
    stat: { value: '24/7', label: 'Scanning' },
    highlights: ['Automated CVE detection', 'Firmware version checks', 'Misconfiguration alerts'],
    cols: 2,
  },
  {
    id: 'encryption',
    icon: Lock,
    color: '#7ab8ff',
    eyebrow: 'Data Security',
    title: 'End-to-End Encryption',
    body: 'All content in transit and at rest is encrypted with AES-256 — from the CMS to the screen, nothing travels in plaintext.',
    stat: { value: 'AES-256', label: 'Encryption' },
    highlights: ['TLS 1.3 in transit', 'AES-256 at rest', 'Zero plaintext exposure'],
    cols: 2,
  },
  {
    id: 'mfa',
    icon: KeyRound,
    color: '#f0a33c',
    eyebrow: 'Identity',
    title: 'Multi-Factor Authentication',
    body: 'Every admin and operator login requires MFA — TOTP, SMS, or hardware key — so a stolen password alone can never unlock your system.',
    stat: { value: 'MFA', label: 'Required' },
    highlights: ['TOTP & hardware key support', 'SSO / SAML compatible', 'Session timeout controls'],
    cols: 2,
  },
  {
    id: 'api',
    icon: Plug,
    color: '#c09aff',
    eyebrow: 'Developer Security',
    title: 'Secure API Access',
    body: "Every API call is authenticated via signed tokens with scoped permissions and rate limiting — so integrations can only touch what they're authorised to.",
    stat: { value: 'OAuth 2.0', label: 'Auth standard' },
    highlights: ['Signed JWT tokens', 'Scoped API permissions', 'Rate limiting & throttling', 'Webhook signature validation'],
    cols: 3,
  },
  {
    id: 'rbac',
    icon: Users,
    color: '#ff8775',
    eyebrow: 'Access Control',
    title: 'Role-Based Access Control',
    body: 'Granular RBAC lets you define exactly who can publish, schedule, or manage screens — by role, location, or team — with no over-permissioning.',
    stat: { value: 'RBAC', label: 'Granular' },
    highlights: ['Custom role definitions', 'Location-scoped permissions', 'Principle of least privilege', 'Audit trail per user'],
    cols: 3,
  },
  {
    id: 'monitoring',
    icon: Activity,
    color: '#60c8f0',
    eyebrow: 'Observability',
    title: 'Real-Time Threat Monitoring',
    body: 'Live dashboards and instant alerts surface anomalies the moment they occur — unusual logins, failed auth attempts, and device health changes.',
    stat: { value: '<1s', label: 'Alert latency' },
    highlights: ['Anomaly detection engine', 'Failed login alerting', 'Device health monitoring', 'SIEM integration ready'],
    cols: 3,
  },
  {
    id: 'audit',
    icon: ClipboardList,
    color: '#00e5a0',
    eyebrow: 'Compliance',
    title: 'Audit Logs & Compliance',
    body: 'Immutable, timestamped audit logs capture every action across your network — ready for GDPR, ISO 27001, and internal compliance reviews.',
    stat: { value: '365d', label: 'Log retention' },
    highlights: ['Immutable log storage', 'GDPR & ISO 27001 aligned', 'Exportable reports', 'Tamper-evident records'],
    cols: 3,
  },
]

// aspects of data protection stuff
export const layers = [
  { label: 'Input validation',   color: '#4ade80', status: 'Passed' },
  { label: 'Auth middleware',    color: '#4ade80', status: 'Passed' },
  { label: 'SQL injection',      color: '#4ade80', status: 'Passed' },
  { label: 'XSS protection',     color: '#fbbf24', status: 'Warning' },
]

export const calls = [
  { method: 'POST', path: '/auth/login',      status: 200 },
  { method: 'GET',  path: '/api/users/me',    status: 200 },
  { method: 'GET',  path: '/api/admin/keys',  status: 401 },
  { method: 'DEL',  path: '/api/screens/12',  status: 403 },
]

export const roles = [
  { role: 'Super Admin',    color: '#f87171', perms: 'Full access' },
  { role: 'Content Editor', color: '#fbbf24', perms: 'Publish only' },
  { role: 'Viewer',         color: '#4ade80', perms: 'Read only' },
]

export const items = [
  {
    id: 'appsec',
    icon: AppWindow,
    color: '#00e5a0',
    eyebrow: 'Application Layer',
    title: 'Application Security',
    body: 'Every request is validated, sanitised, and scanned against known attack vectors — XSS, SQL injection, and CSRF protections built in by default.',
    highlights: ['Input validation on all endpoints', 'XSS & CSRF protection', 'Dependency vulnerability scanning'],
    mockup: 'appsec',
    cols: 2,
  },
  {
    id: 'cloud',
    icon: Cloud,
    color: '#7ab8ff',
    eyebrow: 'Infrastructure',
    title: 'Cloud Security',
    body: 'Your data is distributed across isolated, encrypted cloud regions with automatic failover — no single point of failure, ever.',
    highlights: ['Multi-region isolation', 'Automatic failover', 'Zero-trust network policy'],
    mockup: 'cloud',
    cols: 2,
  },
  {
    id: 'api',
    icon: Plug2,
    color: '#c09aff',
    eyebrow: 'Gateway',
    title: 'API Gateway Protection',
    body: 'Every inbound API call is logged, authenticated, and rate-limited at the gateway — with automatic blocking of suspicious traffic patterns.',
    highlights: ['Request logging & replay protection', 'Rate limiting per key', 'Automatic threat blocking'],
    mockup: 'api',
    cols: 2,
  },
  {
    id: 'iam',
    icon: UserCheck,
    color: '#f0a33c',
    eyebrow: 'Identity',
    title: 'Identity & Access Management',
    body: 'Granular IAM policies ensure every user and service account operates with the minimum permissions required — nothing more.',
    highlights: ['Principle of least privilege', 'Service account scoping', 'SSO & SAML 2.0 support', 'Just-in-time access provisioning'],
    mockup: 'iam',
    cols: 3,
  },
  {
    id: 'data',
    icon: DatabaseZap,
    color: '#5eead4',
    eyebrow: 'Data Protection',
    title: 'Data Encryption & Masking',
    body: 'Sensitive fields are masked at rest and in transit — PII, payment data, and credentials are encrypted end-to-end and never exposed in logs.',
    highlights: ['AES-256 field-level encryption', 'PII masking in all logs', 'GDPR & PCI-DSS aligned', 'Key rotation on schedule'],
    mockup: 'data',
    cols: 3,
  },
]

// Services stuff
export const services = [
  {
    id: 'assessment', span: 2, strong: true,
    icon: ShieldCheck, color: '#f87171',
    pill: 'Step 1', eyebrow: 'Risk Assessment',
    headline: 'Know your exposure before attackers do.',
    body: 'We scan your entire stack — code, dependencies, infrastructure, and configuration — surfacing every exploitable weakness with a clear severity score and a prioritised fix list.',
    bullets: [
      'Full OWASP Top 10 vulnerability scan',
      'Dependency & supply-chain audit',
      'Auth, session & data-exposure checks',
      'Delivered within 48 hours',
    ],
    stats: [['OWASP', 'Top 10'], ['Severity', 'Scored'], ['48h', 'Turnaround']],
  },
  {
    id: 'pentest', span: 1, strong: false,
    icon: Bug, color: '#fbbf24',
    pill: 'Step 2', eyebrow: 'Penetration Testing',
    headline: 'Real attacks. Safe environment.',
    body: 'Ethical hackers probe every layer — network, API, and application — using the same tools and techniques real attackers use, with a full proof-of-concept report.',
    bullets: [
      'Manual + automated exploit attempts',
      'Network, API & app layer coverage',
      'Proof-of-concept for every finding',
    ],
    stats: [['Manual', 'Testing'], ['All', 'Layers'], ['PoC', 'Included']],
  },
  {
    id: 'implementation', span: 1, strong: false,
    icon: Rocket, color: '#a78bfa',
    pill: 'Step 3', eyebrow: 'Secure Implementation',
    headline: 'Fixes shipped, not just listed.',
    body: "We don't hand you a PDF and walk away. Our engineers implement every remediation — hardening config, deploying controls, and verifying the close.",
    bullets: [
      'Firewall rules & network hardening',
      'MFA enforcement & secrets vault setup',
      'SSL/TLS, certs & patch management',
    ],
    stats: [['Hands-On', 'Delivery'], ['Zero', 'Lock-in'], ['Verified', 'Close']],
  },
  {
    id: 'monitoring', span: 2, strong: true,
    icon: Activity, color: '#4ade80',
    pill: 'Step 4', eyebrow: '24/7 Monitoring',
    headline: 'Always watching. Instantly responding.',
    body: 'Continuous threat detection with real-time alerting, full audit logs for compliance, and SLA-backed incident escalation — so nothing slips through.',
    bullets: [
      'Real-time threat detection & alerting',
      'Brute force, port scan & anomaly detection',
      'Full audit log for compliance & forensics',
      'Incident escalation with SLA guarantees',
    ],
    stats: [['24/7', 'Coverage'], ['< 1 min', 'Alert time'], ['Full', 'Audit log']],
  },
]