import {
  ScanSearch,
  LockKeyhole,
  ShieldCheck,
  Plug,
  Users,
  Activity,
  ClipboardList, 
  AppWindow, 
  Cloud, 
  Plug2, 
  UserCheck, 
  DatabaseZap
} from 'lucide-react'

import { AppSecMockup, CloudMockup, ApiMockup, IamMockup, DataMockup } from './ProtectionComponents';

export const features = [
  {
    id: 1,
    icon: ScanSearch,
    accent: '#f87171',
    eyebrow: 'Proactive Defence',
    title: 'Vulnerability Scanning',
    description:'Automated scans continuously probe your network and display infrastructure for weaknesses — flagging misconfigurations, outdated firmware, and exposure points before they can be exploited.',
    highlights: ['Scheduled & on-demand scans', 'Firmware version checks', 'Exposure risk reports'],
    stat: { value: '24/7', label: 'Continuous scanning' },
    wide: true,
  },
  {
    id: 2,
    icon: LockKeyhole,
    accent: '#93c5fd',
    eyebrow: 'Data at Rest & in Transit',
    title: 'Data Encryption',
    description:'All content, credentials, and communications are encrypted end-to-end using AES-256 and TLS 1.3 — ensuring data is unreadable even if intercepted.',
    highlights: ['AES-256 at rest', 'TLS 1.3 in transit', 'Encrypted backups'],
    stat: { value: 'AES-256', label: 'Encryption standard' },
    wide: false,
  },
  {
    id: 3,
    icon: ShieldCheck,
    accent: '#4ade80',
    eyebrow: 'Identity Verification',
    title: 'Multi-Factor Authentication',
    description:'MFA is enforced across all CMS logins and admin panels — adding a second layer of verification that blocks unauthorised access even when credentials are compromised.',
    highlights: ['TOTP & SMS support', 'Enforced for all admins', 'SSO-compatible'],
    stat: { value: 'MFA', label: 'Enforced on all logins' },
    wide: false,
  },
  {
    id: 4,
    icon: Plug,
    accent: '#a78bfa',
    eyebrow: 'Integration Security',
    title: 'Secure APIs',
    description:'Every integration point uses authenticated, rate-limited APIs with token-based access — preventing abuse, injection attacks, and unauthorised data exchange between connected systems.',
    highlights: ['OAuth 2.0 & API tokens', 'Rate limiting enforced', 'Input sanitisation'],
    stat: { value: 'OAuth 2.0', label: 'Auth standard' },
    wide: false,
  },
  {
    id: 5,
    icon: Users,
    accent: '#5eead4',
    eyebrow: 'Least Privilege Access',
    title: 'Role-Based Access Control',
    description:'Define exactly who can view, edit, publish, or manage screens. RBAC ensures staff only access what they need — reducing insider risk and accidental content changes.',
    highlights: ['Custom role definitions', 'Per-screen permissions', 'Audit trail per user'],
    stat: { value: 'RBAC', label: 'Granular permissions' },
    wide: false,
  },
  {
    id: 6,
    icon: Activity,
    accent: '#fbbf24',
    eyebrow: 'Always Watching',
    title: 'Real-Time Threat Monitoring',
    description:'Live dashboards and automated alerts surface anomalies the moment they occur — unusual login attempts, unexpected content changes, or device disconnections trigger instant notifications.',
    highlights: ['Live event dashboard', 'Instant alert notifications', 'Anomaly detection'],
    stat: { value: '<1s', label: 'Alert response time' },
    wide: true,
  },
  {
    id: 7,
    icon: ClipboardList,
    accent: '#fb923c',
    eyebrow: 'Compliance & Assurance',
    title: 'Security Audits',
    description:'Regular third-party and internal audits verify that your signage infrastructure meets industry compliance standards — with full documentation provided for regulatory reporting.',
    highlights: ['Annual third-party audits', 'Compliance documentation', 'Remediation support'],
    stat: { value: 'Annual', label: 'Full audit cycle' },
    wide: true,
  },
];

export const layers = [
    { label: 'Input Validation', status: 'pass', color: '#4ade80' },
    { label: 'Auth Middleware', status: 'pass', color: '#4ade80' },
    { label: 'SQL Injection', status: 'blocked', color: '#f87171' },
    { label: 'XSS Filter', status: 'pass', color: '#4ade80' },
];

export const calls = [
    { method: 'GET', path: '/api/users', status: 200 },
    { method: 'POST', path: '/api/auth', status: 401 },
    { method: 'DELETE', path: '/api/data', status: 403 },
];

export const roles = [
    { role: 'Admin', perms: 'Full access', color: '#f87171' },
    { role: 'Editor', perms: 'Read + Write', color: '#fbbf24' },
    { role: 'Viewer', perms: 'Read only', color: '#4ade80' },
];

export const protections = [
  {
    id: 1,
    icon: AppWindow,
    accent: '#f87171',
    eyebrow: 'App Layer',
    title: 'Application Security',
    description: 'Protect your software at every layer — from input validation and authentication middleware to XSS filtering and SQL injection prevention. Code-level and runtime defences working together.',
    highlights: ['OWASP Top 10 coverage', 'Runtime app self-protection', 'Secure SDLC integration'],
    mockup: AppSecMockup,
    colSpan: 'md:col-span-3',
  },
  {
    id: 2,
    icon: Cloud,
    accent: '#93c5fd',
    eyebrow: 'Infrastructure',
    title: 'Cloud Security',
    description: 'Secure multi-cloud and hybrid environments with continuous posture management, workload protection, and region-level monitoring across all your cloud infrastructure.',
    highlights: ['CSPM & CWPP', 'Multi-region coverage', 'Zero-trust networking'],
    mockup: CloudMockup,
    colSpan: 'md:col-span-3',
  },
  {
    id: 3,
    icon: Plug2,
    accent: '#a78bfa',
    eyebrow: 'Integration Security',
    title: 'API Security',
    description: 'Authenticate, rate-limit, and monitor every API call. Prevent injection attacks, enforce schema validation, and log all gateway traffic for full audit trails.',
    highlights: ['OAuth 2.0 & JWT auth', 'Schema validation', 'Rate limiting & DDoS shield'],
    mockup: ApiMockup,
    colSpan: 'md:col-span-2',
  },
  {
    id: 4,
    icon: UserCheck,
    accent: '#fbbf24',
    eyebrow: 'Access Control',
    title: 'Identity & Access Management',
    description: 'Define and enforce who can access what — with granular role-based permissions, SSO, MFA, and full audit trails for every identity in your organisation.',
    highlights: ['SSO & MFA enforced', 'Granular RBAC', 'Privileged access management'],
    mockup: IamMockup,
    colSpan: 'md:col-span-2',
  },
  {
    id: 5,
    icon: DatabaseZap,
    accent: '#5eead4',
    eyebrow: 'Privacy & Compliance',
    title: 'Data Protection',
    description: 'Encrypt sensitive data at rest and in transit, mask PII in logs, and enforce retention policies — keeping you compliant with GDPR, HIPAA, and industry standards.',
    highlights: ['AES-256 + TLS 1.3', 'PII masking & tokenisation', 'GDPR / HIPAA ready'],
    mockup: DataMockup,
    colSpan: 'md:col-span-2',
  },
];