import { Video, Moon, Bell, Smartphone, Database, Brain, Move, Globe, ArrowRight,
      Camera, Wifi, Activity, LayoutGrid,

 } from 'lucide-react'

export * from "./CCTVStyles";

// Features stuff
export const features = [
  {
    id: 'resolution',
    icon: Video,
    color: '#00e5a0',
    eyebrow: 'Imaging',
    headline: 'HD / 4K Camera Resolution',
    pill: '4K',
    body: 'Crystal-clear footage at up to 4K — every detail captured, day or night, across your entire site.',
    bullets: ['4K Ultra HD sensors', 'H.265 compression', 'Wide dynamic range'],
    stats: [['4K', 'Resolution'], ['120fps', 'Frame rate'], ['HDR', 'Dynamic']],
    cols: 2,
  },
  {
    id: 'ai',
    icon: Brain,
    color: '#c09aff',
    eyebrow: 'Intelligence',
    headline: 'AI-Powered Analytics',
    pill: '99.4%',
    body: 'Intelligent motion detection, facial recognition, and behaviour analysis — turning cameras into proactive security assets.',
    bullets: ['Facial recognition', 'Object & vehicle detection', 'Loitering & perimeter alerts', 'Smart search by attribute'],
    stats: [['99.4%', 'Accuracy'], ['<1s', 'Alert time']],
    cols: 1,
  },
  {
    id: 'night',
    icon: Moon,
    color: '#7ab8ff',
    eyebrow: 'Low-light',
    headline: 'Night Vision',
    pill: '100 m',
    body: 'IR and colour night vision up to 100 m — full clarity in complete darkness, zero compromise.',
    bullets: ['Infrared LEDs', 'Full-colour night mode', '100 m range'],
    stats: [['100m', 'IR range'], ['0 lux', 'Min. light']],
    cols: 1,
  },
  {
    id: 'motion',
    icon: Bell,
    color: '#f0a33c',
    eyebrow: 'Alerts',
    headline: 'Motion Detection',
    pill: 'Real-time',
    body: 'Customisable zones and sensitivity controls that slash false alerts and surface what matters.',
    bullets: ['Custom zone masking', 'Instant push alerts', 'Sensitivity tuning'],
    stats: [['<0.5s', 'Latency'], ['99%', 'Precision']],
    cols: 1,
  },
  {
    id: 'storage',
    icon: Database,
    color: '#ff8775',
    eyebrow: 'Storage',
    headline: 'Cloud & Local Storage',
    pill: 'AES-256',
    body: 'Redundant dual-storage — edge NVR on-site plus encrypted cloud archive for off-site redundancy.',
    bullets: ['30-day cloud retention', 'On-site NVR backup', 'AES-256 encryption'],
    stats: [['30d', 'Cloud'], ['NVR', 'On-site'], ['256', 'AES-bit']],
    cols: 1,
  },
  {
    id: 'remote',
    icon: Smartphone,
    color: '#60c8f0',
    eyebrow: 'Access',
    headline: 'Remote Viewing — Mobile & Web',
    pill: 'Live',
    body: 'Watch any camera live or review recordings from your phone, tablet, or browser — from anywhere in the world.',
    bullets: ['iOS & Android apps', 'Browser-based dashboard', 'Multi-camera grid view'],
    stats: [['iOS', 'App'], ['Android', 'App'], ['Web', 'Browser']],
    cols: 2,
  },
  {
    id: 'ptz',
    icon: Move,
    color: '#c09aff',
    eyebrow: 'Control',
    headline: 'PTZ Control',
    pill: '360°',
    body: 'Pan, tilt, and zoom remotely — 360° coverage with preset patrol routes and intelligent auto-tracking.',
    bullets: ['360° pan & tilt', 'Auto-tracking targets', 'Preset patrol routes'],
    stats: [['360°', 'Coverage'], ['32×', 'Zoom']],
    cols: 1,
  },
  {
    id: 'multilocation',
    icon: Globe,
    color: '#00e5a0',
    eyebrow: 'Scale',
    headline: 'Multi-Location Monitoring',
    pill: 'Unlimited',
    body: 'Manage cameras across multiple sites from one unified dashboard — branches, warehouses, and remote locations with role-based access for your team.',
    bullets: ['Unlimited sites', 'Unified dashboard', 'Role-based access', 'Site grouping'],
    stats: [['∞', 'Sites'], ['RBAC', 'Access'], ['1', 'Dashboard']],
    cols: 3,
  },
]

// Systems Stuff
export const systems = [
  {
    id: 'ip-camera',
    icon: Wifi,
    label: 'Network Based',
    badge: 'Most Popular',
    accentColor: '#00e5a0',
    imageFallbackBg: 'linear-gradient(135deg, #0a2a1f 0%, #0d1f17 100%)',
    image: '/images/max.jpg',
    title: 'IP Camera Systems',
    description:
      'High-definition network cameras that stream and record over your existing LAN or Wi-Fi. Scalable from a single camera to enterprise-grade deployments.',
    highlights: ['4K Resolution', 'PoE Powered', 'Remote Access', 'AI Analytics'],
  },
  {
    id: 'analog-hd',
    icon: Camera,
    label: 'Traditional HD',
    badge: 'Cost Effective',
    accentColor: '#c09aff',
    imageFallbackBg: 'linear-gradient(135deg, #1a0f2e 0%, #130d22 100%)',
    image: '/images/max.jpg',
    title: 'HD Analog / TVI Systems',
    description:
      'Upgrade legacy coax wiring to full HD with TVI/AHD technology. Keep your existing cable runs while getting modern image quality and DVR recording.',
    highlights: ['1080p–8MP', 'Coax Reuse', 'DVR Storage', 'Long Cable Runs'],
  },
  {
    id: 'night-vision',
    icon: Moon,
    label: 'Low-Light',
    badge: 'Night Ready',
    accentColor: '#7ab8ff',
    imageFallbackBg: 'linear-gradient(135deg, #0b1525 0%, #091220 100%)',
    image: '/images/max.jpg',
    title: 'Night Vision Cameras',
    description:
      'IR and colour night-vision cameras that deliver crisp footage in complete darkness. Infrared LEDs illuminate up to 100 m with zero visible light.',
    highlights: ['Starlight Sensor', '100 m IR Range', 'Full-Colour Night', 'Auto IR Cut'],
  },
  {
    id: 'motion-detection',
    icon: Activity,
    label: 'Smart Detection',
    badge: 'AI Powered',
    accentColor: '#f0a33c',
    imageFallbackBg: 'linear-gradient(135deg, #251800 0%, #1c1200 100%)',
    image: '/images/max.jpg',
    title: 'Motion Detection Systems',
    description:
      'AI-driven perimeter protection that distinguishes people, vehicles, and animals from wind and shadows — eliminating false alerts around the clock.',
    highlights: ['Person / Vehicle AI', 'Zone Masking', 'Instant Alerts', 'Event Clips'],
  },
  {
    id: 'remote-viewing',
    icon: Globe,
    label: 'Cloud & Mobile',
    badge: 'Always On',
    accentColor: '#ff8775',
    imageFallbackBg: 'linear-gradient(135deg, #250e0a 0%, #1c0a07 100%)',
    image: '/images/max.jpg',
    title: 'Remote Viewing Systems',
    description:
      'Monitor your property from anywhere in the world via smartphone, tablet, or browser. Encrypted P2P connections with no port-forwarding required.',
    highlights: ['iOS & Android', 'Multi-Site View', 'Cloud Backup', 'Two-Way Audio'],
  },
  {
    id: 'multi-location',
    icon: LayoutGrid,
    label: 'Enterprise',
    badge: 'Multi-Site',
    accentColor: '#60c8f0',
    imageFallbackBg: 'linear-gradient(135deg, #071922 0%, #051318 100%)',
    image: '/images/max.jpg',
    title: 'Multi-Location Systems',
    description:
      'Centralised VMS platforms that unify cameras across multiple branches, warehouses, or sites into one management console with role-based access.',
    highlights: ['Centralised VMS', 'Role-Based Access', 'Cross-Site Search', 'Health Monitoring'],
  },
]